=== wraithlight/wraithlight-mono/applications/packages/tools/tools.schema/src/swagger.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "SWAGGER JSON SCHEMA",
  "description": "Schema for package swagger.json files in the repository.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "enum": [
        "../../../node_modules/@wraithlight/tools.schema/dist/swagger.schema.json"
      ]
    },
    "openapi": {
      "type": "string",
      "enum": [
        "3.0.3"
      ]
    },
    "info": {
      "type": "object",
      "properties": {
        "title": {
          "$ref": "#/components/nonEmptyString"
        },
        "description": {
          "$ref": "#/components/nonEmptyString"
        },
        "version": {
          "$ref": "#/components/nonEmptyString"
        }
      },
      "required": [
        "title",
        "description",
        "version"
      ]
    },
    "servers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "url": {
            "$ref": "#/components/nonEmptyString"
          },
          "description": {
            "type": "string",
            "enum": [
              "dev",
              "local",
              "prod",
              "staging",
              "test"
            ]
          }
        }
      }
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "$ref": "#/components/nonEmptyString"
          },
          "description": {
            "$ref": "#/components/nonEmptyString"
          }
        },
        "additionalProperties": false,
        "required": [
          "name",
          "description"
        ]
      }
    },
    "paths": {
      "type": "object",
      "patternProperties": {
        "^(\\/(external|internal))?\\/api\\/v\\d+\\/*.+": {
          "type": "object",
          "properties": {
            "get": {
              "type": "object",
              "properties": {
                "tags": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/nonEmptyString"
                  }
                },
                "summary": {
                  "$ref": "#/components/nonEmptyString"
                },
                "parameters": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "$ref": "#/components/nonEmptyString"
                      },
                      "in": {
                        "type": "string",
                        "enum": [
                          "path",
                          "query",
                          "header"
                        ]
                      },
                      "required": {
                        "type": "boolean"
                      },
                      "schema": {
                        "type": "object",
                        "properties": {
                          "type": {
                            "$ref": "#/components/nonEmptyString",
                            "enum": [
                              "string",
                              "number",
                              "boolean"
                            ]
                          },
                          "example": {
                            "$ref": "#/components/nonEmptyString"
                          },
                          "format": {
                            "$ref": "#/components/nonEmptyString"
                          }
                        },
                        "required": [
                          "type"
                        ],
                        "additionalProperties": false
                      },
                      "example": {}
                    },
                    "required": [
                      "name",
                      "in",
                      "required",
                      "schema",
                      "example"
                    ],
                    "additionalProperties": false
                  }
                },
                "responses": {
                  "type": "object",
                  "patternProperties": {
                    "(200|400|401|403|404|409|500)": {
                      "$ref": "#/components/generalResponse"
                    },
                    "additionalProperties": false
                  },
                  "additionalProperties": false
                }
              },
              "required": [
                "tags",
                "summary",
                "parameters"
              ],
              "additionalProperties": false
            },
            "post": {
              "type": "object",
              "properties": {
                "tags": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/nonEmptyString"
                  }
                },
                "summary": {
                  "$ref": "#/components/nonEmptyString"
                },
                "parameters": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "$ref": "#/components/nonEmptyString"
                      },
                      "in": {
                        "type": "string",
                        "enum": [
                          "path",
                          "query",
                          "header"
                        ]
                      },
                      "required": {
                        "type": "boolean"
                      },
                      "schema": {
                        "type": "object",
                        "properties": {
                          "type": {
                            "$ref": "#/components/nonEmptyString",
                            "enum": [
                              "string",
                              "number",
                              "boolean"
                            ]
                          },
                          "example": {
                            "$ref": "#/components/nonEmptyString"
                          },
                          "format": {
                            "$ref": "#/components/nonEmptyString"
                          }
                        },
                        "required": [
                          "type"
                        ],
                        "additionalProperties": false
                      },
                      "example": {}
                    },
                    "required": [
                      "name",
                      "in",
                      "required",
                      "schema",
                      "example"
                    ],
                    "additionalProperties": false
                  }
                },
                "responses": {
                  "type": "object",
                  "patternProperties": {
                    "(200|201|202|400|401|403|404|409|500)": {
                      "$ref": "#/components/generalResponse"
                    },
                    "additionalProperties": false
                  },
                  "additionalProperties": false
                },
                "requestBody": {}
              },
              "required": [
                "summary",
                "parameters",
                "tags"
              ],
              "additionalProperties": false
            },
            "patch": {
              "type": "object",
              "properties": {
                "tags": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/nonEmptyString"
                  }
                },
                "summary": {
                  "$ref": "#/components/nonEmptyString"
                },
                "parameters": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "$ref": "#/components/nonEmptyString"
                      },
                      "in": {
                        "type": "string",
                        "enum": [
                          "path",
                          "query",
                          "header"
                        ]
                      },
                      "required": {
                        "type": "boolean"
                      },
                      "schema": {
                        "type": "object",
                        "properties": {
                          "type": {
                            "$ref": "#/components/nonEmptyString",
                            "enum": [
                              "string",
                              "number",
                              "boolean"
                            ]
                          },
                          "example": {
                            "$ref": "#/components/nonEmptyString"
                          },
                          "format": {
                            "$ref": "#/components/nonEmptyString"
                          }
                        },
                        "required": [
                          "type"
                        ],
                        "additionalProperties": false
                      },
                      "example": {}
                    },
                    "required": [
                      "name",
                      "in",
                      "required",
                      "schema",
                      "example"
                    ],
                    "additionalProperties": false
                  }
                },
                "responses": {
                  "type": "object",
                  "patternProperties": {
                    "(200|400|401|403|404|409|500)": {
                      "$ref": "#/components/generalResponse"
                    },
                    "additionalProperties": false
                  },
                  "additionalProperties": false
                },
                "requestBody": {}
              },
              "required": [
                "summary",
                "parameters",
                "tags"
              ],
              "additionalProperties": false
            },
            "delete": {
              "type": "object",
              "properties": {
                "tags": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/nonEmptyString"
                  }
                },
                "summary": {
                  "$ref": "#/components/nonEmptyString"
                },
                "parameters": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "name": {
                        "$ref": "#/components/nonEmptyString"
                      },
                      "in": {
                        "type": "string",
                        "enum": [
                          "path",
                          "query",
                          "header"
                        ]
                      },
                      "required": {
                        "type": "boolean"
                      },
                      "schema": {
                        "type": "object",
                        "properties": {
                          "type": {
                            "$ref": "#/components/nonEmptyString",
                            "enum": [
                              "string",
                              "number",
                              "boolean"
                            ]
                          },
                          "example": {
                            "$ref": "#/components/nonEmptyString"
                          },
                          "format": {
                            "$ref": "#/components/nonEmptyString"
                          }
                        },
                        "required": [
                          "type"
                        ],
                        "additionalProperties": false
                      },
                      "example": {}
                    },
                    "required": [
                      "name",
                      "in",
                      "required",
                      "schema",
                      "example"
                    ],
                    "additionalProperties": false
                  }
                },
                "responses": {
                  "type": "object",
                  "patternProperties": {
                    "(204|400|401|403|404|500)": {
                      "$ref": "#/components/generalResponse"
                    },
                    "additionalProperties": false
                  },
                  "additionalProperties": false
                }
              },
              "required": [
                "tags",
                "summary",
                "parameters"
              ],
              "additionalProperties": false
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    },
    "components": {}
  },
  "additionalProperties": false,
  "required": [
    "$schema",
    "openapi",
    "info",
    "servers",
    "tags",
    "paths"
  ],
  "components": {
    "nonEmptyString": {
      "type": "string",
      "minLength": 1
    },
    "generalResponse": {
      "type": "object",
      "properties": {
        "description": {
          "$ref": "#/components/nonEmptyString"
        },
        "content": {
          "type": "object",
          "properties": {
            "application/json": {
              "type": "object",
              "properties": {
                "schema": {
                  "type": "object",
                  "oneOf": [
                    {
                      "type": "object",
                      "properties": {
                        "$ref": {
                          "$ref": "#/components/nonEmptyString"
                        }
                      }
                    },
                    {
                      "type": "object",
                      "properties": {

                      },
                      "additionalProperties": false
                    }
                  ]
                }
              }
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false,
      "required": [
        "description",
        "content"
      ]
    }
  }
}

=== wraithlight/wraithlight-mono/applications/.swadoc/common/health-check-v2/swagger.json
{
  "$schema": "../../../node_modules/@wraithlight/tools.schema/dist/swagger.schema.json",
  "openapi": "3.0.3",
  "info": {
    "title": "Swagger HC - OpenAPI 3.0",
    "description": "Swagger file for wraithlight's healthcheck controller V2.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://local.auth.wraithlight.ai:4500",
      "description": "local"
    },
    {
      "url": "http://dev.auth.wraithlight.ai:5500",
      "description": "dev"
    },
    {
      "url": "http://test.auth.wraithlight.ai",
      "description": "test"
    },
    {
      "url": "http://staging.auth.wraithlight.ai",
      "description": "staging"
    },
    {
      "url": "http://auth.wraithlight.ai",
      "description": "prod"
    }
  ],
  "tags": [
    {
      "name": "common/healthcheck",
      "description": "Endpoints that are related to external (other microservices) operations. Modifies the user resource."
    }
  ],
  "paths": {
    "/api/v1/health-check/metrics": {
      "get": {
        "operationId": "getHealthCheckMetrics",
        "summary": "Endpoint that return the current metrics.",
        "tags": [
          "common/healthcheck"
        ],
        "parameters": [
          {
            "name": "X-WL-API-TOKEN",
            "in": "header",
            "required": true,
            "example": "bb3a7a80-44ec-4b74-9b7b-c8cd58f777b3",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The operation was successful.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "correlationId": {
                      "type": "string",
                      "format": "uuid",
                      "example": "bb3a7a80-44ec-4b74-9b7b-c8cd58f777b3"
                    },
                    "error": {
                      "type": "object",
                      "properties": {
                        "code": {
                          "type": "string",
                          "example": ""
                        }
                      }
                    },
                    "payload": {
                      "type": "object",
                      "properties": {
                        "numberOfErrorMessages": {
                          "type": "number",
                          "example": 0
                        },
                        "numberOfWarningMessages": {
                          "type": "number",
                          "example": 0
                        },
                        "numberOfInformationMessages": {
                          "type": "number",
                          "example": 0
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error400"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error401"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error500"
                }
              }
            }
          }
        }
      }
    },
    "/api/v1/health-check/health": {
      "get": {
        "operationId": "getHealthCheckHealt",
        "summary": "Endpoint that returns the current status of the API.",
        "tags": [
          "common/healthcheck"
        ],
        "parameters": [
          {
            "name": "X-WL-API-TOKEN",
            "in": "header",
            "required": true,
            "example": "bb3a7a80-44ec-4b74-9b7b-c8cd58f777b3",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The operation was successful.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "correlationId": {
                      "type": "string",
                      "format": "uuid",
                      "example": "bb3a7a80-44ec-4b74-9b7b-c8cd58f777b3"
                    },
                    "error": {
                      "type": "object",
                      "properties": {
                        "code": {
                          "type": "string"
                        }
                      }
                    },
                    "payload": {
                      "type": "object",
                      "properties": {
                        "appName": {
                          "type": "string",
                          "example": "@wraithlight-poc/node.evo"
                        },
                        "appVersion": {
                          "type": "string",
                          "example": "1.0.0"
                        },
                        "uptime": {
                          "type": "number",
                          "example": 178.156131541
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error400"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error401"
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error500"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "error400": {
        "type": "object",
        "properties": {
          "correlationId": {
            "type": "string",
            "format": "uuid",
            "example": "bb3a7a80-44ec-4b74-9b7b-c8cd58f777b3"
          },
          "error": {
            "type": "object",
            "properties": {
              "code": {
                "type": "string",
                "example": "E_USER_NOT_FOUND"
              }
            }
          },
          "payload": {
            "type": "object",
            "properties": {}
          }
        }
      },
      "error401": {
        "type": "object",
        "properties": {
          "correlationId": {
            "type": "string",
            "format": "uuid",
            "example": "bb3a7a80-44ec-4b74-9b7b-c8cd58f777b3"
          },
          "error": {
            "type": "object",
            "properties": {
              "code": {
                "type": "string",
                "example": "E_USER_NOT_FOUND"
              }
            }
          },
          "payload": {
            "type": "object",
            "properties": {}
          }
        }
      },
      "error500": {
        "type": "object",
        "properties": {
          "correlationId": {
            "type": "string",
            "format": "uuid",
            "example": "bb3a7a80-44ec-4b74-9b7b-c8cd58f777b3"
          },
          "error": {
            "type": "object",
            "properties": {
              "code": {
                "type": "string",
                "example": "E_USER_NOT_FOUND"
              }
            }
          },
          "payload": {
            "type": "object",
            "properties": {}
          }
        }
      }
    }
  }
}

=== wraithlight/wraithlight-mono/applications/.swadoc/common/latency/swagger.json
{
  "$schema": "../../../node_modules/@wraithlight/tools.schema/dist/swagger.schema.json",
  "openapi": "3.0.3",
  "info": {
    "title": "Swagger Latency - OpenAPI 3.0",
    "description": "Swagger file for wraithlight's latency controller V1.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://local.auth.wraithlight.ai:4500",
      "description": "local"
    },
    {
      "url": "http://dev.auth.wraithlight.ai:5500",
      "description": "dev"
    },
    {
      "url": "http://test.auth.wraithlight.ai",
      "description": "test"
    },
    {
      "url": "http://staging.auth.wraithlight.ai",
      "description": "staging"
    },
    {
      "url": "http://auth.wraithlight.ai",
      "description": "prod"
    }
  ],
  "tags": [
    {
      "name": "common/latency",
      "description": "Endpoints that are related to latency entity."
    }
  ],
  "paths": {
    "/api/v1/latency": {
      "get": {
        "operationId": "getLatency",
        "summary": "Endpoint that returns the latency.",
        "tags": [
          "common/latency"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "The operation was successful.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "correlationId": {
                      "type": "string",
                      "format": "uuid",
                      "example": "bb3a7a80-44ec-4b74-9b7b-c8cd58f777b3"
                    },
                    "error": {
                      "type": "object",
                      "properties": {
                        "code": {
                          "type": "string",
                          "example": ""
                        }
                      }
                    },
                    "payload": {
                      "type": "object",
                      "properties": {
                        "receivedAtUtc": {
                          "type": "string",
                          "format": "datetime",
                          "example": "2024-09-29T10:55:45.889Z"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/error500"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "error500": {
        "type": "object",
        "properties": {
          "correlationId": {
            "type": "string",
            "format": "uuid",
            "example": "bb3a7a80-44ec-4b74-9b7b-c8cd58f777b3"
          },
          "error": {
            "type": "object",
            "properties": {
              "code": {
                "type": "string",
                "example": "E_INTERNAL"
              }
            }
          },
          "payload": {
            "type": "object",
            "properties": {}
          }
        }
      }
    }
  }
}
